apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-namespace

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: frontend
          image: 824033491491.dkr.ecr.ap-south-1.amazonaws.com/frontend:8

          ports:
            - containerPort: 80
          env:
            - name: DT_NODE_ID
              value: "Test-V1"
