apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: my-namespace   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      imagePullSecrets:
        - name: ecr-secret 
      containers:
        - name: service-registry
          image: 824033491491.dkr.ecr.ap-south-1.amazonaws.com/service-registry:2
          ports:
            - containerPort: 8761
