apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: group-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/Seethanveshi-git/splitwise-k8s-manifests.git
    targetRevision: main
    path: group-service

  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace-test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
